import { useMemo, useState } from "react";

export default function DataTable({ columns, rows, rowKey = "id", searchPlaceholder = "Search records…", emptyText = "No records found." }) {
  const [query,setQuery]=useState(""); const [sort,setSort]=useState({key:columns[0]?.key,direction:"asc"}); const [page,setPage]=useState(1); const [size,setSize]=useState(10);
  const filtered=useMemo(()=>{const value=query.trim().toLowerCase();if(!value)return rows;return rows.filter(row=>columns.some(column=>String(column.searchValue?column.searchValue(row):row[column.key]??"").toLowerCase().includes(value)));},[rows,columns,query]);
  const sorted=useMemo(()=>[...filtered].sort((a,b)=>{const av=a[sort.key]??"",bv=b[sort.key]??"";return String(av).localeCompare(String(bv),undefined,{numeric:true})*(sort.direction==="asc"?1:-1);}),[filtered,sort]);
  const pages=Math.max(1,Math.ceil(sorted.length/size));const current=Math.min(page,pages);const visible=sorted.slice((current-1)*size,current*size);
  const order=key=>{setSort(s=>({key,direction:s.key===key&&s.direction==="asc"?"desc":"asc"}));setPage(1);};
  return <div><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder={searchPlaceholder} className="min-w-60 flex-1 rounded-xl border px-4 py-2.5"/><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}} className="rounded-xl border px-3 py-2.5"><option value="10">10 rows</option><option value="25">25 rows</option><option value="50">50 rows</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b bg-slate-50">{columns.map(column=><th key={column.key} className="whitespace-nowrap p-3"><button type="button" disabled={column.sortable===false} onClick={()=>order(column.key)} className="font-semibold">{column.label}{sort.key===column.key?sort.direction==="asc"?" ↑":" ↓":""}</button></th>)}</tr></thead><tbody>{visible.map(row=><tr key={row[rowKey]} className="border-b last:border-0 hover:bg-slate-50">{columns.map(column=><td key={column.key} className="p-3 align-top">{column.render?column.render(row):row[column.key]??"—"}</td>)}</tr>)}</tbody></table>{visible.length===0&&<p className="p-8 text-center text-slate-500">{emptyText}</p>}</div><div className="mt-4 flex items-center justify-between text-sm text-slate-500"><span>{filtered.length?`${(current-1)*size+1}–${Math.min(current*size,filtered.length)} of ${filtered.length}`:"0 records"}</span><div className="flex gap-2"><button disabled={current<=1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Previous</button><span className="px-2 py-1.5">{current} / {pages}</span><button disabled={current>=pages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Next</button></div></div></div>;
}
