import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getContent, updateContent } from "../../api/content";
import { deleteScene, downloadSceneMedia, reorderScenes, updateScene } from "../../api/scene";
import { assetUrl } from "../../api/axios";
import ContentFinisher from "../ai/ContentFinisher";
import SceneMediaUpload from "../../components/SceneMediaUpload";

export default function ContentEditor() {
  const { id } = useParams(); const [content,setContent]=useState(null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const load=async()=>{const result=await getContent(id); setContent(result.content||result.data||result);}; useEffect(()=>{load().catch(()=>setMessage("Unable to load content."));},[id]);
  const field=(name,value)=>setContent(c=>({...c,[name]:value}));
  const save=async(status=content.status)=>{setBusy(true);setMessage("");try{await updateContent(id,{title:content.title,hook:content.hook,script:content.script,caption:content.caption,hashtags:Array.isArray(content.hashtags)?content.hashtags.join(","):content.hashtags,keywords:Array.isArray(content.keywords)?content.keywords.join(","):content.keywords,cta:content.cta,language:content.language,status});await Promise.all(content.scenes.map(scene=>updateScene(scene.id,{title:scene.title,text:scene.text,voice_text:scene.voice_text||scene.text,duration:Number(scene.duration)||5,transition:scene.transition||"fade"})));setContent(c=>({...c,status}));setMessage(status==="approved"?"Content approved and ready to schedule.":"Changes saved.");}catch(e){setMessage(e.response?.data?.detail||"Save failed.");}finally{setBusy(false);}};
  const sceneField=(sceneId,name,value)=>setContent(c=>({...c,scenes:c.scenes.map(s=>s.id===sceneId?{...s,[name]:value}:s)}));
  const move=async(index,direction)=>{const next=[...content.scenes];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setContent(c=>({...c,scenes:next}));await reorderScenes(id,next.map(s=>s.id));};
  const remove=async(sceneId)=>{if(!window.confirm("Delete this scene?"))return;await deleteScene(sceneId);setContent(c=>({...c,scenes:c.scenes.filter(s=>s.id!==sceneId)}));};
  const replace=async(sceneId)=>{setBusy(true);try{await downloadSceneMedia(sceneId);await load();setMessage("Scene media replaced.");}catch(e){setMessage(e.response?.data?.detail||"Media replacement failed.");}finally{setBusy(false);}};
  if(!content)return <div className="p-8">{message||"Loading editor…"}</div>;
  const textFields=[["title","Title",1],["hook","Hook",2],["script","Script / voiceover",5],["caption","Caption",4],["hashtags","Hashtags",2],["keywords","Keywords",2],["cta","Call to action",2]];
  return <div className="p-1 sm:p-4 lg:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link to="/history" className="text-sm text-indigo-600">← History</Link><h1 className="mt-2 text-3xl font-bold">Content Editor</h1><p className="text-slate-500">Edit, review, approve, render, then schedule.</p></div><span className="rounded-full bg-slate-100 px-4 py-2 text-sm capitalize">{content.status}</span></div>
  {message&&<p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm">{message}</p>}<section className="mt-6 rounded-2xl bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2">{textFields.map(([name,label,rows])=><label key={name} className={rows>2?"md:col-span-2":""}><span className="text-sm font-semibold">{label}</span><textarea rows={rows} value={Array.isArray(content[name])?content[name].join(", "):content[name]||""} onChange={e=>field(name,e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label>)}</div><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>save("draft")} className="rounded-xl border px-4 py-2">Save draft</button><button disabled={busy} onClick={()=>save("needs_review")} className="rounded-xl bg-amber-500 px-4 py-2 text-white">Send to review</button><button disabled={busy} onClick={()=>save("approved")} className="rounded-xl bg-emerald-600 px-4 py-2 text-white">Approve</button><Link to="/voice" className="rounded-xl bg-indigo-100 px-4 py-2 text-indigo-700">Voice studio</Link><Link to="/scheduler" className="rounded-xl bg-slate-900 px-4 py-2 text-white">Schedule</Link></div></section>
  <h2 className="mt-8 text-xl font-bold">Scenes</h2><div className="mt-3 space-y-4">{content.scenes.map((scene,index)=><article key={scene.id} className="grid gap-4 rounded-2xl bg-white p-4 shadow-sm md:grid-cols-[160px_1fr]"><div>{scene.media_url?(scene.media_type === "video" ? <video src={assetUrl(scene.media_url)} controls preload="metadata" className="h-40 w-full rounded-xl object-contain" /> : <img src={assetUrl(scene.media_url)} alt={`Scene ${index+1}`} className="h-40 w-full rounded-xl object-cover" />):<div className="h-40 rounded-xl bg-slate-100"/>}<button disabled={busy} onClick={()=>replace(scene.id)} className="mt-2 w-full rounded-lg border px-2 py-1 text-xs">Find stock media</button><SceneMediaUpload sceneId={scene.id} disabled={busy} onBusyChange={setBusy} onUploaded={result=>setContent(current=>({...current,scenes:current.scenes.map(item=>item.id===scene.id?{...item,media_id:result.media_id,media_url:result.media_url,media_type:result.media_type,media_provider:result.media_provider,status:result.status}:item)}))}/></div><div className="space-y-3"><div className="flex justify-between"><strong>Scene {index+1}</strong><div className="flex gap-1"><button onClick={()=>move(index,-1)} className="border px-2">↑</button><button onClick={()=>move(index,1)} className="border px-2">↓</button><button onClick={()=>remove(scene.id)} className="px-2 text-red-600">Delete</button></div></div><textarea value={scene.text||""} onChange={e=>sceneField(scene.id,"text",e.target.value)} rows={3} className="w-full rounded-xl border p-3"/><div className="grid gap-2 sm:grid-cols-2"><label className="text-sm">Duration<input type="number" min="1" max="60" value={scene.duration||5} onChange={e=>sceneField(scene.id,"duration",e.target.value)} className="ml-2 w-20 rounded border p-2"/></label><select value={scene.transition||"fade"} onChange={e=>sceneField(scene.id,"transition",e.target.value)} className="rounded border p-2"><option>fade</option><option>cut</option><option>slide</option></select></div></div></article>)}</div>
  <ContentFinisher content={content} username={content.branding?.username} logo={content.branding?.logo} projectId={content.project_id}/></div>;
}
